import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "antd/dist/antd.css"
import Advices from "../components/Advices"
import Search from "../components/Search"

export default function Home() {
  return (
    <div /*className={styles.container}*/>
      <Head>
        <title>Examen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Advices />
        <Search />
        

      </div>

      

      
    </div>
  )
}
