import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { DatePicker } from 'antd'
import "antd/dist/antd.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Examen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <DatePicker />

      </div>

      

      
    </div>
  )
}
